using Confluent.SchemaRegistry;
using Confluent.SchemaRegistry.Serdes;

namespace MinimalKafka.Serialization;

internal sealed class AvroMessageSerializer(ISchemaRegistryClient client, AvroSerializerConfig? config)
    : SchemaRegistryMessageSerializer
{
    public override string Format => MessageFormats.Avro;

    protected override string TypeRequirement =>
        "use a class generated by avrogen (ISpecificRecord) or Avro.Generic.GenericRecord.";

    protected override IKafkaSerializer CreateAdapter(Type type) => Build(nameof(Create), type);

    private KafkaSerializer<T> Create<T>() where T : class =>
        new(new AvroSerializer<T>(client, config), new AvroDeserializer<T>(client));
}
