namespace MinimalKafka.Serialization;

internal sealed class ProtobufMessageSerializer(ISchemaRegistryClient client, ProtobufSerializerConfig? config)
    : SchemaRegistryMessageSerializer
{
    public override string Format => MessageFormats.Protobuf;

    protected override string TypeRequirement =>
        "use a message class generated by protoc (IMessage<T> with a parameterless constructor).";

    protected override Adapter CreateAdapter(Type type) => Build(nameof(Create), type);

    private Adapter Create<T>() where T : class, IMessage<T>, new() =>
        new Adapter<T>(new ProtobufSerializer<T>(client, config), new ProtobufDeserializer<T>());
}
