using Confluent.SchemaRegistry;
using Confluent.SchemaRegistry.Serdes;
using Google.Protobuf;

namespace MinimalKafka.Serialization;

internal sealed class ProtobufMessageSerializer(ISchemaRegistryClient client, ProtobufSerializerConfig? config)
    : SchemaRegistryMessageSerializer
{
    public override string Format => MessageFormats.Protobuf;

    protected override string TypeRequirement =>
        "use a message class generated by protoc (IMessage<T> with a parameterless constructor).";

    protected override IKafkaSerializer CreateAdapter(Type type) => Build(nameof(Create), type);

    private KafkaSerializer<T> Create<T>() where T : class, IMessage<T>, new() =>
        new(new ProtobufSerializer<T>(client, config), new ProtobufDeserializer<T>());
}
