using Confluent.Kafka;

namespace MinimalKafka.Metadata;

/// <summary>
/// Represents metadata for handling consumer events in a Kafka consumer.
/// </summary>
[AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
public class ConsumerHandlerMetadataAttribute : Attribute
{
    /// <summary>
    /// Handles the event when partitions are assigned to the consumer. This function is called with the list of assigned partitions and should return a list of <see cref="TopicPartitionOffset"/> indicating the offsets to start consuming from.
    /// </summary>
    public Func<object, List<TopicPartition>, IEnumerable<TopicPartitionOffset>> PartitionsAssignedHandler { get; internal set; }
        = (_, partitions) =>
        {
            Console.WriteLine($"Assigned partitions: [{string.Join(", ", partitions)}]");
            // Default behavior: return the assigned partitions with unset offset
            return partitions.Select(p => new TopicPartitionOffset(p, Offset.Unset));
        };

    /// <summary>
    /// Handles the event when partitions are lost by the consumer. This function is called with the list of lost partitions and should return a list of <see cref="TopicPartitionOffset"/> indicating the offsets to start consuming from after the loss.
    /// </summary>
    public Func<object, List<TopicPartitionOffset>, IEnumerable<TopicPartitionOffset>> PartitionsLostHandler { get; internal set; }
        = (_, partitions) =>
        {
            Console.WriteLine($"Lost partitions: [{string.Join(", ", partitions)}]");
            return [];
        };

    /// <summary>
    /// Handles the event when partitions are revoked from the consumer. This action is called with the list of revoked partitions and can be used to perform any necessary cleanup or logging.
    /// </summary>
    public Action<object, List<TopicPartitionOffset>> PartitionsRevokedHandler { get; internal set; }
        = (_, part) =>
        {
            foreach (var p in part)
            {
                Console.WriteLine($"[REVOKED] {p.Topic} - {p.Partition}");
            }
        };

    /// <summary>
    /// Handles the event when statistics are generated by the consumer. This action is called with a string containing the statistics information, which can be logged or processed as needed.
    /// </summary>
    public Action<object, string> StatisticsHandler { get; internal set; }
        = (_, e) => Console.WriteLine($"[STATS] {e}");

    /// <summary>
    /// Handles the event when an error occurs in the consumer. This action is called with an <see cref="Confluent.Kafka.Error"/> object containing details about the error, which can be logged or processed as needed.
    /// </summary>
    public Action<object, Error> ErrorHandler { get; internal set; }
        = (_, e) => Console.WriteLine($"[{GetLocal(e)}] {e.Code} - {e.Reason}");

    private static string GetLocal(Error e)
    {
        string logVar = string.Empty;
        if (e.IsLocalError)
        {
            logVar = $"{logVar}LOCAL";
        }
        if (e.IsBrokerError)
        {
            logVar = $"{logVar}BROKER";
        }

        return logVar;
    }

    /// <summary>
    /// Handles the event when a log message is generated by the consumer. This action is called with a <see cref="LogMessage"/> object containing details about the log message, which can be logged or processed as needed.
    /// </summary>
    public Action<object, LogMessage> LogHandler { get; internal set; }
        = (_, e) => Console.WriteLine($"[{e.Level}] {e.Name} - {e.Message}");

    /// <summary>
    /// Handles the event when an OAuth bearer token needs to be refreshed. This action is called with a string containing the token information, which can be logged or processed as needed.
    /// </summary>
    public Action<object, string> OAuthBearerTokenRefreshHandler { get; internal set; } = (_, e) => Console.WriteLine($"[OAUTH] {e}");
}


/// <summary>
/// Represents metadata for handling producer events in a Kafka producer.
/// </summary>
[AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
public class ProducerHandlerMetadataAttribute : Attribute
{
    /// <summary>
    /// Handles the event when statistics are generated by the producer. This action is called with a string containing the statistics information, which can be logged or processed as needed.
    /// </summary>
    public Action<object, string> StatisticsHandler { get; internal set; }
        = (_, e) => Console.WriteLine($"[STATS] {e}");

    /// <summary>
    /// Handles the event when an error occurs in the producer. This action is called with an <see cref="Confluent.Kafka.Error"/> object containing details about the error, which can be logged or processed as needed.
    /// </summary>
    public Action<object, Error> ErrorHandler { get; internal set; }
        = (_, e) => Console.WriteLine($"[{GetLocal(e)}] {e.Code} - {e.Reason}");

    /// <summary>
    /// Gets a string representation of the error type (local or broker) for logging purposes.
    /// </summary>
    /// <param name="e">The error object containing details about the error.</param>
    /// <returns>A string representing the error type.</returns>
    private static string GetLocal(Error e)
    {
        string logVar = string.Empty;
        if (e.IsLocalError)
        {
            logVar = $"{logVar}LOCAL";
        }
        if (e.IsBrokerError)
        {
            logVar = $"{logVar}BROKER";
        }
        return logVar;
    }

    /// <summary>
    /// Handles the event when a log message is generated by the producer. This action is called with a <see cref="LogMessage"/> object containing details about the log message, which can be logged or processed as needed.
    /// </summary>
    public Action<object, LogMessage> LogHandler { get; internal set; }
        = (_, e) => Console.WriteLine($"[{e.Level}] {e.Name} - {e.Message}");

    /// <summary>
    /// Handles the event when an OAuth bearer token needs to be refreshed for the producer. This action is called with a string containing the token information, which can be logged or processed as needed.
    /// </summary>
    public Action<object, string> OAuthBearerTokenRefreshHandler { get; internal set; } = (_, e) => Console.WriteLine($"[OAUTH] {e}");
}